# encoding: utf-8
# Version 0.0.1

Vagrant.configure("2") do |config|

  # The box to be used on the environment.
  # For more boxes, search here: https://atlas.hashicorp.com/search.
  config.vm.box = 'hashicorp/precise32'

  # Network configuration.
  config.vm.network :forwarded_port, guest: 3000, host: 3000 # Rails
  config.vm.network :forwarded_port, guest: 5432, host: 5432 # Postgres
  config.vm.network :forwarded_port, guest: 1080, host: 1080 # Mailcatcher
  config.vm.network :forwarded_port, guest: 6379, host: 6379 # Redis

  # SSH Agent
  config.ssh.forward_agent = true

  # Shared folders
  config.vm.synced_folder "../devbox/", "/devbox", create: true

  # Provisions
  config.vm.provision :shell, :path => "essentials.sh"
  config.vm.provision :shell, :path => "git.sh"
  config.vm.provision :shell, :path => "nodejs.sh"
  config.vm.provision :shell, :path => "sqlite3.sh"
  config.vm.provision :shell, :path => "postgres.sh"
  config.vm.provision :shell, :path => "redis.sh"
  config.vm.provision :shell, :path => "rvm.sh"
  config.vm.provision :shell, :path => "heroku.sh"
  config.vm.provision :shell, :path => "dot_profile.sh"
  config.vm.provision :shell, :path => "permissions.sh"
end
